name: CI

on: [push, pull_request]

jobs:
  validate:
    name: GHC ${{ matrix.ghc }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.6', '8.8', '8.10', '9.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.4.0.0'

      - name: Build
        run: cabal build

      - name: Test
        run: cabal test parsley-tests-and-bench --enable-tests

      - name: Doc
        run: cabal haddock --enable-doc

