name: CI

on: [push, pull_request]

jobs:
  validate:
    name: GHC ${{ matrix.ghc }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.6', '8.8', '8.10', '9.0']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Setup Haskell
        uses: haskell/actions/setup@v1.2.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.4.0.0'

      - name: Build
        run: cabal build parsley --enable-tests --enable-doc

      - name: Test
        run: cabal test parsley --enable-tests --enable-doc

      - name: Doc
        run: cabal haddock parsley --enable-tests --enable-doc
